# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/bob/projects/c10t

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /media/data/projects/c10t

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /media/data/projects/c10t/CMakeFiles /media/data/projects/c10t/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /media/data/projects/c10t/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named c10t

# Build rule for target.
c10t: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 c10t
.PHONY : c10t

# fast build rule for target.
c10t/fast:
	$(MAKE) -f src/CMakeFiles/c10t.dir/build.make src/CMakeFiles/c10t.dir/build
.PHONY : c10t/fast

#=============================================================================
# Target rules for targets named c10t-debug

# Build rule for target.
c10t-debug: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 c10t-debug
.PHONY : c10t-debug

# fast build rule for target.
c10t-debug/fast:
	$(MAKE) -f src/CMakeFiles/c10t-debug.dir/build.make src/CMakeFiles/c10t-debug.dir/build
.PHONY : c10t-debug/fast

#=============================================================================
# Target rules for targets named c10t-lib

# Build rule for target.
c10t-lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 c10t-lib
.PHONY : c10t-lib

# fast build rule for target.
c10t-lib/fast:
	$(MAKE) -f src/CMakeFiles/c10t-lib.dir/build.make src/CMakeFiles/c10t-lib.dir/build
.PHONY : c10t-lib/fast

#=============================================================================
# Target rules for targets named c10t-test

# Build rule for target.
c10t-test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 c10t-test
.PHONY : c10t-test

# fast build rule for target.
c10t-test/fast:
	$(MAKE) -f test/CMakeFiles/c10t-test.dir/build.make test/CMakeFiles/c10t-test.dir/build
.PHONY : c10t-test/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... c10t"
	@echo "... c10t-debug"
	@echo "... c10t-lib"
	@echo "... c10t-test"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

