#ifndef HAVE_CONFIG_H
#define HAVE_CONFIG_H

#cmakedefine C10T_VERSION "@C10T_VERSION@"
#cmakedefine C10T_SITE "@C10T_SITE@"
#cmakedefine C10T_CONTACT "@C10T_CONTACT@"
#cmakedefine C10T_DISABLE_THREADS "@C10T_DISABLE_THREADS@"

#endif /* HAVE_CONFIG_H */
